###### Create a docker image for tif2pdf util
# 
#Commande à lancer
#
FROM alpine:latest
MAINTAINER Eric Grammatico <eric@grammatico.me>
LABEL name="alpine/tif2pdf"

RUN apk --no-cache add imagemagick tesseract-ocr tesseract-ocr-data-fra ghostscript

